# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Blocstagram' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Blocstagram
  pod 'UICKeyChainStore'	

  target 'BlocstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlocstagramUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
